import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Modal from "@/components/modals/Modal";

const font = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Sheol-Blogs",
  description: "Blogs generated by AI"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Modal isOpen actionLabel="Submit" />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
